apiVersion: apps/v1
kind: Deployment
metadata:
  name: theamleaf-k8s-deployment
spec:
  selector:
    matchLabels:
      app: theamleaf-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: theamleaf-k8s
    spec:
      containers:
      - name: theamleaf-k8s
        image: 900896635518.dkr.ecr.ap-south-1.amazonaws.com/thymeleaf:latest
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: theamleaf-k8s-svc
spec:
  selector:
    app: theamleaf-k8s
  ports:
  - protocol: "TCP"
    port: 8089
    targetPort: 8089
  type: LoadBalancer
